### ISSUE TITLE
Autocompletion ? 

### ISSUE THREAD

**Issue by cecilpert** [alkihis/interactive-cli-helper#1]
Oui bonjour une suggestion je sais pas si c'est possible/simple de l'ajouter, mais avoir l'autocompletion si on veut donner des fichiers en argument par exemple ce serait incroyable !

**Comment by alkihis** [comment]
EDIT: J'en ai fait un [paquet trouvable ici](https://github.com/alkihis/interactive-cli-helper-file-suggestor).

Les instructions sont dans le README !

---

Bonjour Cécile, effectivement, c'est possible :D 
Quand on définit une commande, on peut écrire un suggesteur (fonction de suggestion) personnalisé.

-> Ici, cette solution requiert l'installation du paquet 'glob' (https://www.npmjs.com/package/glob)
```ts
import glob from 'glob';
import { CliSuggestor } from 'interactive-cli-helper';

export const fileSuggestor: CliSuggestor = (rest: string) => {
  // If path is relative, add ./ to help glob :)
  const filepath = rest.startsWith('/') ? rest : ('./' + rest);
  // Get all items beginning by input string
  const results = glob.sync(filepath + '*', {
    dot: true,
    mark: true,
  });

  // Slice the possible ./ at the beginning of the string
  return results.map(path => path.startsWith('./') ? path.slice('./'.length) : path);
};

// -----------
// Import and use this file suggestor function on command that await a file in parameter
// -----------
cli.command('read', filename => {
  // example
  console.log(fs.readFileSync(filename, 'utf-8'));
}, {
  // -v- Magic happens here !
  onSuggest: fileSuggestor,
});
```

Dis moi si c'est ce que tu attends.

**Comment by anaiscb** [comment]
Bonjour,
Ca fonctionne très bien et c'est exactement ce qu'il fallait, merci !
